### ISSUE TITLE
Create pipeline for applications

### ISSUE THREAD

**Issue by sammybigbux** [sammybigbux/JobTracker#26]
- [x] Have a few examples of different types of resume    _for examle Generative AI resume or Machine LEarning engineer resume, or Data Scientist/Analyst resume_
- [x] Have a few example Cover Letters
- [x] Offer your experiences as a sort of "grab bag" of acomplishments and terms, in the form of a list of descriptions with bold titles
- [x] Find a way to privatize your LinkedIn (so that you can let someone else take control)

**Comment by sammybigbux** [comment]
Slightly different, employee will:

- Find a job role on LinkedIn based on: https://docs.google.com/document/d/1Kb4kvCHzG0mGv45ypCc5FkmPz_LbUJMB8NnO8SkNhMw/edit
- Write cover letter based on: https://drive.google.com/drive/folders/1xe6FSFoBurFeDltkmIQUVsddoYAAEcuE
- Edit resume based on: https://drive.google.com/drive/folders/1QOpMJOrEuKdINQTJ9B5oKj2Dykbd7VAT
- Add resume to: https://drive.google.com/drive/folders/1QOpMJOrEuKdINQTJ9B5oKj2Dykbd7VAT
- Add cover letter to: https://drive.google.com/drive/folders/1AtK05USBGDeLX6agpkxU2CuCXo4Wfz5N
- Write down details on: https://docs.google.com/spreadsheets/d/1go1H9vBZafLQMySH4mme8RhYVfvDN4MCEdC2FnXXSso/edit#gid=0
