### ISSUE TITLE
Make prospect list

### ISSUE THREAD

**Issue by sammybigbux** [sammybigbux/JobTracker#31]
I'd like 25-30 prospects (companies that I want to work for). For each of the following I want

- [ ] Company name
- [ ] Reason for applying (as in, something you can mention to a potential connection).
- [ ] Scale (1-10) of how much I'd like to work for them.
- [ ] Closest 3 contacts (either someone you know, mutually know, or someone at the grunt level)
- [ ] Follow company on linkedin

I'd like to aim for 10 nonprofits, 10 Generative AI / Deep learning companies, and 10 special interest companies.
